### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by chunchiahuang** [WavX/bioacoustics#1]
Dear sir and madam.

I failed to install bioacoustics to my laptop and got this error message:
"Error: running command '"C:/PROGRA~1/R/R-34~1.4/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 2"

The environment is R 3.4.4 and R studio V 1.0.143, Windows 7. The problem happened in both 32 and 64 bit R.

Many thanks

Joe

**Comment by ygc2l** [comment]
Do you have development tools installed?

**Comment by chunchiahuang** [comment]
Hi Jean,

I did install the latest Rtools

thanks :)

Joe

Joe Chun-Chia Huang
Postdoc Research Fellow, Biodiversity Research Center Academia Sinica

Address: Room C208, Interdisciplinary Research Building
No. 28, Lane 70, Yanjiuyuan Rd Sec 2, Nan-gang District, Taipei City 115,
Taiwan
E-mail: ecojoe.huang@gmail.com
Office: +886-2-7872-294
Mobile (TW): +886-905-046-643

**Comment by chunchiahuang** [comment]
Hi jean,

I mean I did installed the Rtool but still have the problem. Thanks again

**Comment by ygc2l** [comment]
Oh, sorry about that...

First, make sure you have `knitr` and `rmarkdown` installed if you are installing the package with the vignette. If that doesn't work can you install the package in a temp directory, for example using the following command `install_github("wavx/bioacoustics", out_dir = "C:/bioacoustics")` and upload the .out file.
