### ISSUE TITLE
write_zc does not include GUANO md

### ISSUE THREAD

**Issue by abfleishman** [WavX/bioacoustics#13]
I am working with ZC files from Wildlife Acoustics Kaleidoscope software which implants guano metadata.  When I use `read_zc` the guano data is found and saved in `zc$metadata$guano` but when I use `write_zc` the guano metadata is not written and I get a warning.  I have attached an example file in this zip.
[U6232138.zip](https://github.com/WavX/bioacoustics/files/6650768/U6232138.zip)

```
zc<-read_zc( "U6232138.51#")
write_zc(zc,filename ="U6232138.zc" )
```
>Warning message:
>In raw[7:281] <- update_header.zc(zc$metadata$file) :
>  number of items to replace is not a multiple of replacement length

Is it possible to write guano metadata into these zc files from the `bioacoustics` package?

**Comment by ygc2l** [comment]
Hi,

Unfortunately, it is not yet possible to write GUANO metadata with zero-crossing files using the `bioacoustics` package.

**Comment by abfleishman** [comment]
Ok.  Thanks for your reply.  I assume that based on your use of "yet" means that there might be some development in the future, but is it not a priority??

**Comment by ygc2l** [comment]
Exactly, we have other priorities at the moment, but contributions are always welcome :).
