### ISSUE TITLE
Tutorial - download data from  https://www.xeno-canto.org/ fails

### ISSUE THREAD

**Issue by paddygoat** [WavX/bioacoustics#5]
> library(warbleR)
> df1 = quer_xc(qword ='Catharus bicknelli type:call cnt:"United States"', download = FALSE)

  |                                                  | 0 % ~calculating  Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

> 
>

**Comment by ygc2l** [comment]
Looks like this is an issue with the warbleR package. We contacted the warbleR package maintainer. Thanks for the report.
