### ISSUE TITLE
Any reason why it's not part of CRAN anymore?

### ISSUE THREAD

**Issue by spatialaudiolabs** [WavX/bioacoustics#8]
Testing out the package, it's pretty cool, hitting some walls here and there, readWave is not working now (not sure why, seewave and tuneR are there and called) but will sort it out. 

I would just like to make sure people are still working on this, which it seems like :)

Thank you
Axel

**Comment by ygc2l** [comment]
Hi Axel,

We are working on a fix and will submit to CRAN soon. In the meantime, I suggest you install the package using the following command `devtools::install_github("wavx/bioacoustics")`.

Jean
